/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.obligatorio2;

import java.awt.Color;

/**
 *
 * @author guille
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IngreseTiempo = new javax.swing.JLabel();
        Planificador = new javax.swing.JLabel();
        DeProcesos = new javax.swing.JLabel();
        TextFieldTiempo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        IngreseCantidad = new javax.swing.JLabel();
        TextFieldCantidad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngreseTiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngreseTiempo.setForeground(new java.awt.Color(0, 0, 0));
        IngreseTiempo.setText("Ingrese la cantidad de tiempo por proceso:");
        jPanel1.add(IngreseTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        Planificador.setFont(new java.awt.Font("HP Simplified Hans", 0, 36)); // NOI18N
        Planificador.setForeground(new java.awt.Color(0, 0, 0));
        Planificador.setText("PLANIFICADOR");
        jPanel1.add(Planificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        DeProcesos.setFont(new java.awt.Font("HP Simplified Hans", 0, 36)); // NOI18N
        DeProcesos.setForeground(new java.awt.Color(0, 0, 0));
        DeProcesos.setText("DE PROCESOS");
        jPanel1.add(DeProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        TextFieldTiempo.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldTiempo.setForeground(new java.awt.Color(204, 204, 204));
        TextFieldTiempo.setText("Tiempo");
        TextFieldTiempo.setBorder(null);
        TextFieldTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldTiempoMouseClicked(evt);
            }
        });
        jPanel1.add(TextFieldTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, -1));

        IngreseCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngreseCantidad.setForeground(new java.awt.Color(0, 0, 0));
        IngreseCantidad.setText("Ingrese la cantidad de procesadores:");
        jPanel1.add(IngreseCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        TextFieldCantidad.setEditable(false);
        TextFieldCantidad.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCantidad.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldCantidad.setText("1");
        TextFieldCantidad.setBorder(null);
        jPanel1.add(TextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, -1));

        jPanel3.setBackground(new java.awt.Color(3, 68, 46));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 240, 360));

        jButton1.setBackground(new java.awt.Color(3, 100, 46));
        jButton1.setFont(new java.awt.Font("HP Simplified Hans", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldTiempoMouseClicked
        TextFieldTiempo.setText("");
        TextFieldTiempo.setForeground(Color.black);
    }//GEN-LAST:event_TextFieldTiempoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON INICIO
        long tiempo = Long.parseLong(TextFieldTiempo.getText());
        Manejador mane = new Manejador(tiempo);
        mane.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeProcesos;
    private javax.swing.JLabel IngreseCantidad;
    private javax.swing.JLabel IngreseTiempo;
    private javax.swing.JLabel Planificador;
    private javax.swing.JTextField TextFieldCantidad;
    private javax.swing.JTextField TextFieldTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
