/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.obligatorio2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author guille
 */
public class Manejador extends javax.swing.JFrame {

    SistemaOperativo SO;
    DefaultListModel ListaAgregar = new DefaultListModel();
    public final static int INTERVAL = 10;
    public final static int INTERVAL2 = 1;
    public long tiempo;
    
    /**
     * Creates new form Manejador
     * @param tiempo
     */
    public Manejador(long tiempo) {
        this.tiempo = tiempo;
        initComponents();
        SO = new SistemaOperativo(tiempo);
        timerIniciar.start();
        ListaAgregar.clear();
        jList1.setModel(ListaAgregar);
    }

    
    Timer timer = new Timer(INTERVAL, new ActionListener() {
    public void actionPerformed(ActionEvent evt) {
        enCPU2.setText(SO.enCPU());
        }    
    });
    
    Timer timerIniciar = new Timer(INTERVAL2, new ActionListener() {
    public void actionPerformed(ActionEvent evt) {
        SO.Iniciar();
        }    
    });
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerde = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BotonCargarProcesos = new javax.swing.JButton();
        PidProceso = new javax.swing.JTextField();
        BotonCrearProceso = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Texto_ID = new javax.swing.JLabel();
        PPrioridad = new javax.swing.JComboBox<>();
        Texto_Prioridad = new javax.swing.JLabel();
        Texto_TipoProceso = new javax.swing.JLabel();
        PTipoProceso = new javax.swing.JComboBox<>();
        Texto_TiempoDeEjecucion = new javax.swing.JLabel();
        PTFinalizar = new javax.swing.JTextField();
        Texto_IntervaloES = new javax.swing.JLabel();
        PIntervaloES = new javax.swing.JTextField();
        Texto_TiempoES = new javax.swing.JLabel();
        PTiempoES = new javax.swing.JTextField();
        PIntervaloES1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        porcentaje = new javax.swing.JLabel();
        enCPU2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVerde.setBackground(new java.awt.Color(3, 68, 46));
        PanelVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("HP Simplified Hans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Creador de Procesos");
        PanelVerde.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jList1.setBackground(new java.awt.Color(3, 100, 46));
        jList1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        PanelVerde.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, -1));

        BotonCargarProcesos.setBackground(new java.awt.Color(3, 100, 46));
        BotonCargarProcesos.setFont(new java.awt.Font("HP Simplified Hans", 0, 12)); // NOI18N
        BotonCargarProcesos.setForeground(new java.awt.Color(255, 255, 255));
        BotonCargarProcesos.setText("Cargar Procesos");
        BotonCargarProcesos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonCargarProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarProcesosActionPerformed(evt);
            }
        });
        PanelVerde.add(BotonCargarProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 120, 30));

        PidProceso.setBackground(new java.awt.Color(3, 100, 46));
        PidProceso.setForeground(new java.awt.Color(255, 255, 255));
        PidProceso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PidProceso.setText("1");
        PidProceso.setBorder(null);
        PanelVerde.add(PidProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));

        BotonCrearProceso.setBackground(new java.awt.Color(3, 100, 46));
        BotonCrearProceso.setFont(new java.awt.Font("HP Simplified Hans", 0, 12)); // NOI18N
        BotonCrearProceso.setForeground(new java.awt.Color(255, 255, 255));
        BotonCrearProceso.setText("CREAR");
        BotonCrearProceso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonCrearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearProcesoActionPerformed(evt);
            }
        });
        PanelVerde.add(BotonCrearProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("HP Simplified Hans", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Procesos Creados:");
        PanelVerde.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        Texto_ID.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_ID.setForeground(new java.awt.Color(255, 255, 255));
        Texto_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_ID.setText("ID:");
        Texto_ID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelVerde.add(Texto_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, 30));

        PPrioridad.setBackground(new java.awt.Color(3, 100, 46));
        PPrioridad.setForeground(new java.awt.Color(255, 255, 255));
        PPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        PanelVerde.add(PPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, 30));

        Texto_Prioridad.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_Prioridad.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Prioridad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Prioridad.setText("Prioridad:");
        PanelVerde.add(Texto_Prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, 30));

        Texto_TipoProceso.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_TipoProceso.setForeground(new java.awt.Color(255, 255, 255));
        Texto_TipoProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_TipoProceso.setText("Tipo de proceso:");
        PanelVerde.add(Texto_TipoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 30));

        PTipoProceso.setBackground(new java.awt.Color(3, 100, 46));
        PTipoProceso.setForeground(new java.awt.Color(255, 255, 255));
        PTipoProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "SO" }));
        PanelVerde.add(PTipoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 30));

        Texto_TiempoDeEjecucion.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_TiempoDeEjecucion.setForeground(new java.awt.Color(255, 255, 255));
        Texto_TiempoDeEjecucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_TiempoDeEjecucion.setText("Tiempo de ejec:");
        PanelVerde.add(Texto_TiempoDeEjecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, 30));

        PTFinalizar.setBackground(new java.awt.Color(3, 100, 46));
        PTFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        PTFinalizar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PTFinalizar.setText("10000");
        PTFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTFinalizarActionPerformed(evt);
            }
        });
        PanelVerde.add(PTFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, 30));

        Texto_IntervaloES.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_IntervaloES.setForeground(new java.awt.Color(255, 255, 255));
        Texto_IntervaloES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_IntervaloES.setText("Intervalo E/S:");
        PanelVerde.add(Texto_IntervaloES, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        PIntervaloES.setBackground(new java.awt.Color(153, 153, 153));
        PIntervaloES.setForeground(new java.awt.Color(0, 0, 0));
        PIntervaloES.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PIntervaloES.setText("ID");
        PIntervaloES.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanelVerde.add(PIntervaloES, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 20));

        Texto_TiempoES.setFont(new java.awt.Font("HP Simplified Hans", 0, 14)); // NOI18N
        Texto_TiempoES.setForeground(new java.awt.Color(255, 255, 255));
        Texto_TiempoES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_TiempoES.setText("Tiempo E/S:");
        PanelVerde.add(Texto_TiempoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 110, 30));

        PTiempoES.setBackground(new java.awt.Color(3, 100, 46));
        PTiempoES.setForeground(new java.awt.Color(255, 255, 255));
        PTiempoES.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PTiempoES.setText("1000");
        PanelVerde.add(PTiempoES, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, 30));

        PIntervaloES1.setBackground(new java.awt.Color(3, 100, 46));
        PIntervaloES1.setForeground(new java.awt.Color(255, 255, 255));
        PIntervaloES1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PIntervaloES1.setText("8000");
        PanelVerde.add(PIntervaloES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 30));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bloquear");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVerde.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 110, 20));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Desbloquear");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVerde.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 100, 20));

        getContentPane().add(PanelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 350, 580));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentaje.setForeground(new java.awt.Color(0, 0, 0));
        porcentaje.setText("Porcentaje");
        jPanel3.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        enCPU2.setForeground(new java.awt.Color(0, 0, 0));
        enCPU2.setText("                                                                                                                                                                                                                    ");
        jPanel3.add(enCPU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearProcesoActionPerformed
        SO.crearProceso(PidProceso.getText(), PPrioridad.getSelectedItem().toString(), PTipoProceso.getSelectedItem().toString(), PTFinalizar.getText(), PIntervaloES.getText(), PTiempoES.getText());
        ListaAgregar.addElement(PidProceso.getText());
        jList1.setModel(ListaAgregar);
    }//GEN-LAST:event_BotonCrearProcesoActionPerformed

    private void BotonCargarProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarProcesosActionPerformed
        SO.cargarProcesos();
        timer.start();
        ListaAgregar.clear();
        jList1.setModel(ListaAgregar);
    }//GEN-LAST:event_BotonCargarProcesosActionPerformed

    private void PTFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manejador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manejador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manejador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manejador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manejador(1).setVisible(true);
            }
        });
    }
    
    public void Setup(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCargarProcesos;
    private javax.swing.JButton BotonCrearProceso;
    private javax.swing.JTextField PIntervaloES;
    private javax.swing.JTextField PIntervaloES1;
    private javax.swing.JComboBox<String> PPrioridad;
    private javax.swing.JTextField PTFinalizar;
    private javax.swing.JTextField PTiempoES;
    private javax.swing.JComboBox<String> PTipoProceso;
    private javax.swing.JPanel PanelVerde;
    private javax.swing.JTextField PidProceso;
    private javax.swing.JLabel Texto_ID;
    private javax.swing.JLabel Texto_IntervaloES;
    private javax.swing.JLabel Texto_Prioridad;
    private javax.swing.JLabel Texto_TiempoDeEjecucion;
    private javax.swing.JLabel Texto_TiempoES;
    private javax.swing.JLabel Texto_TipoProceso;
    private javax.swing.JLabel enCPU2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel porcentaje;
    // End of variables declaration//GEN-END:variables
}
